config/routes.rb
Rails.application.routes.draw do

  
  
  get 'home/welcome'

  root 'home#welcome'
 
   resources :user_types
   resources :pqr_types
 
  resources :pqrs do
  resources :comments, only:[:create, :destroy, :update]
  end
   devise_for :users, :controllers => {:registrations => "users/registrations"}
 
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/controllers/pqr_types_controller.rb
class PqrTypesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pqr_type, only: [:show, :edit, :update, :destroy]

  # GET /pqr_types
  # GET /pqr_types.json
  def index
    @pqr_type = PqrType.all
  end

  # GET /pqr_types/1
  # GET /pqr_types/1.json
  def show
  end

  # GET /pqr_types/new
  def new
     @pqr_type = PqrType.new     
  end

  # GET /pqr_types/1/edit
  def edit
  end

  # POST /pqr_types
  # POST /pqr_types.json
  def create
    @pqr_type = PqrType.new(pqr_type_params)

    respond_to do |format|
      if @pqr_type.save
        format.html { redirect_to @pqr_type, notice: 'Pqr type was successfully created.' }
        format.json { render :show, status: :created, location: @pqr_type }
      else
        format.html { render :new }
        format.json { render json: @pqr_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pqr_types/1
  # PATCH/PUT /pqr_types/1.json
  def update
    respond_to do |format|
      if @pqr_type.update(pqr_type_params)
        format.html { redirect_to @pqr_type, notice: 'Pqr type was successfully updated.' }
        format.json { render :show, status: :ok, location: @pqr_type }
      else
        format.html { render :edit }
        format.json { render json: @pqr_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pqr_types/1
  # DELETE /pqr_types/1.json
  def destroy
    @pqr_type.destroy
    respond_to do |format|
      format.html { redirect_to pqr_types_url, notice: 'Pqr type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pqr_type
      @pqr_type = PqrType.find(params[:id])
    end
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def pqr_type_params
      params.require(:pqr_type).permit(:name, :day)
    end

end

app/helpers/pqr_types_helper.rb
module PqrTypesHelper
end

app/views/pqr_types/_form.html.erb
<%= form_with(model: pqr_type, local: true) do |form| %>
  <% if pqr_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pqr_type.errors.count, "error") %> prohibited this pqr_type from being saved:</h2>

      <ul>
      <% pqr_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :pqr_type_name %>
  </div>

  <div class="field">
    <%= form.label :day %>
    <%= form.number_field :day, id: :pqr_type_day %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pqr_types/edit.html.erb
<h1>Editing Pqr Type</h1>

<%= render 'form', pqr_type: @pqr_type %>

<%= link_to 'Show', @pqr_type %> |
<%= link_to 'Back', pqr_types_path %>

app/views/pqr_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pqr Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pqr_type.each do |pqr_type| %>
      <tr>
        <td><%= pqr_type.name %></td>
        <td><%= pqr_type.day %></td>
        <td><%= link_to 'Show', pqr_type %></td>
        <td><%= link_to 'Edit', edit_pqr_type_path(pqr_type) %></td>
        <td><%= link_to 'Destroy', pqr_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pqr Type', new_pqr_type_path %>

app/views/pqr_types/new.html.erb
<h1>New Pqr Type</h1>

<%= render 'form', pqr_type: @pqr_type %>

<%= link_to 'Back', pqr_types_path %>

app/views/pqr_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pqr_type.name %>
</p>

<p>
  <strong>Day:</strong>
  <%= @pqr_type.day %>
</p>

<%= link_to 'Edit', edit_pqr_type_path(@pqr_type) %> |
<%= link_to 'Back', pqr_types_path %>