config/routes.rb
Rails.application.routes.draw do

  
  
  get 'home/welcome'

  root 'home#welcome'
 
   resources :user_types
   resources :pqr_types
 
  resources :pqrs do
  resources :comments, only:[:create, :destroy, :update]
  end
   devise_for :users, :controllers => {:registrations => "users/registrations"}
 
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/pqr.rb
class Pqr < ApplicationRecord
    belongs_to :user
    belongs_to :pqr_type
    has_many :comments
    has_attached_file :myfile
    validates_attachment_content_type :myfile, content_type: ["application/pdf","application/xlsx","application/docx","application/doc","image/jpg","image/jpeg"] 
end

app/models/pqr_type.rb
class PqrType < ApplicationRecord
   has_many :pqrs
end

app/controllers/pqrs_controller.rb
class PqrsController < ApplicationController
before_action :authenticate_user!
  before_action :set_pqr, only: [:show, :edit, :update, :destroy]


def download_file
# redirect_to paperclip_attachment.file.url
end
  # GET /pqrs
  # GET /pqrs.json
  def index
    @pqrs = Pqr.all
  end

  # GET /pqrs/1
  # GET /pqrs/1.json
  def show
    @comment = Comment.new

  end

  # GET /pqrs/new
  def new
    @pqr = Pqr.new
    @pqr_type = PqrType.all
  end

  # GET /pqrs/1/edit
  def edit
  end
 
  # POST /pqrs
  # POST /pqrs.json
  def create
    @pqr = current_user.pqrs.new(pqr_params)

    respond_to do |format|
      if @pqr.save
        format.html { redirect_to @pqr, notice: 'Pqr was successfully created.' }
        format.json { render :show, status: :created, location: @pqr }
      else
        format.html { render :new }
        format.json { render json: @pqr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pqrs/1
  # PATCH/PUT /pqrs/1.json
  def update
    respond_to do |format|
      if @pqr.update(pqr_params)
        format.html { redirect_to @pqr, notice: 'Pqr was successfully updated.' }
        format.json { render :show, status: :ok, location: @pqr }
      else
        format.html { render :edit }
        format.json { render json: @pqr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pqrs/1
  # DELETE /pqrs/1.json
  def destroy
    @pqr.destroy
    respond_to do |format|
      format.html { redirect_to pqrs_url, notice: 'Pqr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pqr
        @pqr = Pqr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pqr_params
      params.require(:pqr).permit(:subject, :content, :pqr_type_id)
    end
end

app/helpers/pqrs_helper.rb
module PqrsHelper
end

app/views/pqrs/_form.html.erb
<%= form_with(model: pqr, local: true) do |form| %>
  <% if pqr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pqr.errors.count, "error") %> prohibited this pqr from being saved:</h2>

      <ul>
      <% pqr.errors.full_messages.each do |message| %>
      
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <div class ="field">
  <%= form.label :"PQR type" %>
    <% @pqr_type.each do |pqr_type| %>
    <div class = "field">
        <%= check_box_tag "pqr[pqr_type_id]", pqr_type.id %> <%= pqr_type.name %>
    </div>
    <% end %>
  </div>
  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject, id: :pqr_subject %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :pqr_content %>
  </div>

  <div class="field">
             
     <%=label_tag "document","Adjunt document (Only *.pdf, *.xlsx, *.word *.jpg)"%>
     <%= form.file_field :myfile %>
             
     </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pqrs/edit.html.erb
<h1>Editing Pqr</h1>

<%= render 'form', pqr: @pqr %>

<%= link_to 'Show', @pqr %> |
<%= link_to 'Back', pqrs_path %>

app/views/pqrs/index.html.erb
<h1>Pqrs</h1>

<table>
  <thead>
    <tr>
    <th>PQR type</th>
      <th>Subject</th>
      <th>Content</th>
       <th>Created to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pqrs.each do |pqr| %>
      <tr>
       <td><%= pqr.pqr_type.name %></td>
        <td><%= pqr.subject %></td>
        <td><%= pqr.content %></td>
         <td><%= pqr.user.email %></td>
        <td><%= link_to 'Show', pqr %></td>
        <td><%= link_to 'Edit', edit_pqr_path(pqr) %></td>
        <td><%= link_to 'Destroy', pqr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pqr', new_pqr_path %>

app/views/pqrs/new.html.erb
<h1>New Pqr</h1>


<%= render 'form', pqr: @pqr %>

<%= link_to 'Back', pqrs_path %>

app/views/pqrs/show.html.erb
<p>
  <strong>PQR_type:</strong>
  <%= @pqr.pqr_type.name %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @pqr.subject %>
</p>

<p>
  <strong>Content:</strong>
  <%= @pqr.content %>
</p>

<div class="field">
    <strong>Comments</strong>
    <%= render "comments/form" %>
    <ul>
        <% @pqr.comments.each do |comment| %>
        <li>
            <% comment.body%> -- <%comment.user.email%>
        </li>
        <% end %>
    </ul>
</div>

<%= link_to 'Edit', edit_pqr_path(@pqr) %> |
<%= link_to 'Back', pqrs_path %>